### ISSUE TITLE
A problem about the wrappers

### ISSUE THREAD

**Issue by shinshiner** [pathak22/noreward-rl#13]
Hello, I am very interested in this repo and I want to reproduct the result. However, when I run the `train.py` in child mode(I am not familiar with tmux), it report an error that 
```
Traceback (most recent call last):
  File "worker.py", line 188, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "worker.py", line 180, in main
    run(args, server)
  File "worker.py", line 27, in run
    noLifeReward=args.noLifeReward)
  File "/home/shin/noreward-rl/src/envs.py", line 23, in create_env
    return create_mario(env_id, client_id, **kwargs)
  File "/home/shin/noreward-rl/src/envs.py", line 106, in create_mario
    env = modewrapper(acwrapper(env))
  File "/home/shin/noreward-rl/src/ppaquette_gym_super_mario/wrappers/action_space.py", line 31, in __init__
    self.action_space = gym.spaces.multi_discrete.DiscreteToMultiDiscrete(self.action_space, mapping)
AttributeError: module 'gym.spaces.multi_discrete' has no attribute 'DiscreteToMultiDiscrete'
```

It seems that the environment encounts some problems, have you met this error ? I can use `gym.spaces.multi_discrete.DiscreteToMultiDiscrete` in my other python script. Do you have some ideas about this issue ?

**Comment by pathak22** [comment]
This is gym version issue. But if you follow the instructions in ReadMe exactly, it should not come. Seems like you installed gym separately manually.

**Comment by shinshiner** [comment]
OK, I tried the whole process again and now I can successfully run the training code, thank you very much !
