### ISSUE TITLE
getting install error

### ISSUE THREAD

**Issue by rnunziata** [pathak22/noreward-rl#26]
getting install error running requierments.txt, any idea on how to resolve this error:

```
  Could not build doom-py: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/home/rjn/projects/RL/noreward-rl/curiosity/bin/python', '-DPYTHON_LIBRARY=/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/usr/include/python2.7']' returned non-zero exit status 1. (HINT: are you sure cmake is installed? You might also be missing a library. Try running 'apt-get install -y python-numpy cmake zlib1g-dev libjpeg-dev libboost-all-dev gcc libsdl2-dev wget unzip'
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-aEKIPe/doom-py/setup.py", line 88, in <module>
      include_package_data=True,
    File "/home/rjn/projects/RL/noreward-rl/curiosity/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/rjn/projects/RL/noreward-rl/curiosity/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-aEKIPe/doom-py/setup.py", line 63, in run
      build_func()
    File "/tmp/pip-install-aEKIPe/doom-py/setup.py", line 41, in build_linux
      build_common('so')
    File "/tmp/pip-install-aEKIPe/doom-py/setup.py", line 28, in build_common
      subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH={}'.format(sys.executable)] + cmake_arg_list, cwd='doom_py')
    File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DBUILD_JAVA=OFF', '-DPYTHON_EXECUTABLE:FILEPATH=/home/rjn/projects/RL/noreward-rl/curiosity/bin/python', '-DPYTHON_LIBRARY=/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so', '-DPYTHON_INCLUDE_DIR=/usr/include/python2.7']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for doom-py
  Running setup.py clean for doom-py
Failed to build doom-py
docker-py 1.10.3 has requirement requests<2.11,>=2.5.2, but you'll have requests 2.18.1 which is incompatible.
```

**Comment by rnunziata** [comment]
resloved ...my error.

**Comment by wxtyixiao** [comment]
The same error in my installation of doom-py.
So, could you tell me how you solved the error?
Thank you very much.

**Comment by rnunziata** [comment]
sorry i've forgotten how  I resolved it I think the I was trying to do the pip install outside the virtual environment.

this is what I have:


```
(curiosity) pip show requests

Name: requests
Version: 2.18.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/rjn/projects/RL/noreward-rl/curiosity/lib/python2.7/site-packages
Requires: certifi, chardet, urllib3, idna
Required-by: docker-py, gym



(curiosity)  pip show docker-py

Name: docker-py
Version: 1.10.3
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/rjn/projects/RL/noreward-rl/curiosity/lib/python2.7/site-packages
Requires: backports.ssl-match-hostname, docker-pycreds, requests, ipaddress, websocket-client, six
Required-by: universe

```

**Comment by wxtyixiao** [comment]
The error occurred in installing doom-py and ppaquette-gym-doom packages, 
Thank you very much for your reply.

**Comment by wxtyixiao** [comment]
Excuse me, could you tell me the your virtualenv is python2.x or python3.x ?

**Comment by rnunziata** [comment]
(curiosity) $ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
