### ISSUE TITLE
Tryinf to run simple atari pong 

### ISSUE THREAD

**Issue by rnunziata** [pathak22/noreward-rl#34]
Ran got a checkpoint but can no visualization  the inference failed see below. tried running with more than one worker same error.

```
python train.py --env-id Pong-ram-v0 --num-workers 1  --visualise 


('w-0', "tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /home/rjn/projects/RL/noreward-rl/curiosity/bin/python worker.py --log-dir /tmp/Pong-ram-v0 --env-id Pong-ram-v0 --num-workers 1 --psPort 12222 --visualise --designHead universe --job-name worker --task 0 --remotes 1' Enter")
Executing the following commands:
mkdir -p /tmp/Pong-ram-v0
echo /home/rjn/projects/RL/noreward-rl/curiosity/bin/python train.py --env-id Pong-ram-v0 --num-workers 1 --visualise > /tmp/Pong-ram-v0/cmd.sh


kill -9 $( lsof -i:12345 -t ) > /dev/null 2>&1
kill -9 $( lsof -i:12222-12223 -t ) > /dev/null 2>&1
tmux kill-session -t a3c
tmux new-session -s a3c -n ps -d bash
tmux new-window -t a3c -n w-0 bash
tmux new-window -t a3c -n tb bash
tmux new-window -t a3c -n htop bash
sleep 1
tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /home/rjn/projects/RL/noreward-rl/curiosity/bin/python worker.py --log-dir /tmp/Pong-ram-v0 --env-id Pong-ram-v0 --num-workers 1 --psPort 12222 --visualise --designHead universe --job-name ps' Enter
tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /home/rjn/projects/RL/noreward-rl/curiosity/bin/python worker.py --log-dir /tmp/Pong-ram-v0 --env-id Pong-ram-v0 --num-workers 1 --psPort 12222 --visualise --designHead universe --job-name worker --task 0 --remotes 1' Enter
tmux send-keys -t a3c:tb 'tensorboard --logdir /tmp/Pong-ram-v0 --port 12345' Enter
tmux send-keys -t a3c:htop htop Enter

Use `tmux attach -t a3c` to watch process output
Use `tmux kill-session -t a3c` to kill the job
Point your browser to http://localhost:12345 to see Tensorboard
```

`(curiosity) rjn@rjn-Oryx-Pro:~/projects/RL/noreward-rl/src$ tmux kill-session -t a3c`

```
(curiosity) rjn@rjn-Oryx-Pro:~/projects/RL/noreward-rl/src$ python src/inference.py --default --env-id Pong-ram-v0 --record
python: can't open file 'src/inference.py': [Errno 2] No such file or directory
(curiosity) rjn@rjn-Oryx-Pro:~/projects/RL/noreward-rl/src$ python inference.py --default --env-id Pong-ram-v0 --record
[2018-11-07 10:50:31,304] Writing logs to file: /tmp/universe-5865.log
[2018-11-07 10:50:31,545] Making new env: Pong-ram-v0
[2018-11-07 10:50:31,696] Creating monitor directory /tmp/Pong-ram-v0/inference
Using universe head design
[2018-11-07 10:50:31,959] Trainable vars:
[2018-11-07 10:50:31,959]   global/l1/W:0 (3, 3, 1, 32)
[2018-11-07 10:50:31,959]   global/l1/b:0 (1, 1, 1, 32)
[2018-11-07 10:50:31,959]   global/l2/W:0 (3, 3, 32, 32)
[2018-11-07 10:50:31,959]   global/l2/b:0 (1, 1, 1, 32)
[2018-11-07 10:50:31,960]   global/l3/W:0 (3, 3, 32, 32)
[2018-11-07 10:50:31,960]   global/l3/b:0 (1, 1, 1, 32)
[2018-11-07 10:50:31,960]   global/l4/W:0 (3, 3, 32, 32)
[2018-11-07 10:50:31,960]   global/l4/b:0 (1, 1, 1, 32)
[2018-11-07 10:50:31,960]   global/RNN/BasicLSTMCell/Linear/Matrix:0 (544, 1024)
[2018-11-07 10:50:31,960]   global/RNN/BasicLSTMCell/Linear/Bias:0 (1024,)
[2018-11-07 10:50:31,960]   global/value/w:0 (256, 1)
[2018-11-07 10:50:31,960]   global/value/b:0 (1,)
[2018-11-07 10:50:31,960]   global/action/w:0 (256, 6)
[2018-11-07 10:50:31,960]   global/action/b:0 (6,)
[2018-11-07 10:50:31,962] Inference events directory: /tmp/Pong-ram-v0/inference
[2018-11-07 10:50:31,963] Initializing all parameters.
[2018-11-07 10:50:32,058] Restoring trainable global parameters.
[2018-11-07 10:50:32,067] Restored model was trained for 0.00M global steps
[2018-11-07 10:50:32,067] Called reset on <Unvectorize<VectorizeFilter[<class 'envs.DiagnosticsInfoI'>]<AtariRescale42x42<Vectorize<Monitor<TimeLimit<AtariEnv instance>>>>>>> before configuring. Configuring automatically with default arguments
[2018-11-07 10:50:32,075] Starting new video recorder writing to /tmp/Pong-ram-v0/inference/openaigym.video.0.5865.video000000.mp4
Traceback (most recent call last):
  File "inference.py", line 216, in <module>
    tf.app.run()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "inference.py", line 213, in main
    inference(args)
  File "inference.py", line 88, in inference
    last_state = env.reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/gym/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/universe/universe/wrappers/vectorize.py", line 46, in _reset
    observation_n = self.env.reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/gym/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/universe/universe/vectorized/vectorize_filter.py", line 29, in _reset
    observation_n = self.env.reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/gym/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/home/rjn/projects/RL/noreward-rl/curiosity/src/gym/gym/core.py", line 376, in _reset
    return self._observation(observation)
  File "/home/rjn/projects/RL/noreward-rl/src/envs.py", line 294, in _observation
    return [_process_frame42(observation) for observation in observation_n]
  File "/home/rjn/projects/RL/noreward-rl/src/envs.py", line 276, in _process_frame42
    frame = frame[34:34+160, :160]
IndexError: too many indices for array
[2018-11-07 10:50:32,201] Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/Pong-ram-v0/inference')

```

**Comment by rnunziata** [comment]
closed running wrong this works:
```
python worker.py --log-dir /tmp/SpaceInvaders-ram-v0 --env-id Pong-v0 --num-workers 1 --visualise  --job-name==ps &
python worker.py --log-dir /tmp/SpaceInvaders-ram-v0 --env-id Pong-v0 --num-workers 1 --visualise  --job-name=worker
```
